name = "memoize"
main = "src/index.js"
compatibility_date = "2024-06-08"
workers_dev = true

[build]
command = ""
watch_dir = ["src", "packages"]

[[d1_databases]]
binding = "DB"
database_name = "memoize-db"
database_id = "66e97f47-9227-4ca1-b282-1fbc5c476cd7"

[vars]
GOOGLE_CLIENT_ID = "1028165377413-sf6qst1qh8pc27ba8qt089eist9am7fb.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET = "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"
GOOGLE_REDIRECT_URI = "https://memoize.cards/auth/callback"
HOST = "https://memoize.cards"

[dev]
ip = "localhost"
port = 8787
