name = "memoize"
main = "src/index.js"
compatibility_date = "2024-06-08"
workers_dev = true

[build]
command = ""
watch_dir = ["src", "packages"]

[[kv_namespaces]]
binding = "DECK"
id = "dbdafa7aadb544f68c6ee70b97b76cd1"

[[kv_namespaces]]
binding = "CARD"
id = "e6542a45fa2d4ac0bc9d36cd4eb62f38"

[vars]
GOOGLE_CLIENT_ID = "1028165377413-sf6qst1qh8pc27ba8qt089eist9am7fb.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET = "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"
GOOGLE_REDIRECT_URI = "https://memoize.cards/auth/callback"
HOST = "https://memoize.cards"

[dev]
ip = "localhost"
port = 8787
